sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  # - cp themes/_config.yml themes/icarus/_config.yml
  # - cp themes/assets/img/* themes/icarus/source/images/
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  # fqdn: st3inum.github.io
  on:
    branch: master
  local-dir: public