title: tree
author: steinum
menus: 
  关于: /about
links:
  github: https://github.com/st3inum
favicon: /favicon.ico
# valine 
valine:
    # 评论
    # need to change if want to active valine
    enableComment: false  
    # 阅读量
    enableCounter: false
    # valine appID
    appID: 
    # valine appKey
    appKey: 
    placeholder: comment
    avatar: retro
# 是否开启“不蒜子”统计访问量
busuanzi: true
# 底部版权开始年份
siteStartYear: 2019